### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by ZhangChao1993** [edward3862/CariMe-pytorch#1]
Could you share us the pretrained models? Thanks for your great work.

**Comment by edward3862** [comment]
> Could you share us the pretrained models? Thanks for your great work.

Hi, this repo is not the final version of our work. We have planned to release the pre-trained model but I'm recently busy with another work. We'll update the repo and release the pretrained model as soon as possible. Thanks again for your attention.

**Comment by edward3862** [comment]
@ZhangChao1993 Hi there, the pretrained models are uploaded.
